Repository jdhernandezS1/Summer_Hackaton, pull requests merged in 2023-07, with the labels that each got.

#24 Add landing page initial section
  .vscode/settings.json
  dashboard/templates/dashboard/index.html
  templates/base.html
Labels: Front

#34 Replicate initial landing design
  README.md
  static/css/style.css
  static/images/mosaic-images-webp-smaller/amos.webp
  static/images/mosaic-images-webp-smaller/deniz-altindas.webp
  static/images/mosaic-images-webp-smaller/eneko-urunuela.webp
  static/images/mosaic-images-webp-smaller/fons-heijnsbroek.webp
  static/images/mosaic-images-webp-smaller/gabriella-clare-marino.webp
  static/images/mosaic-images-webp-smaller/k-mitch-hodge.webp
  static/images/mosaic-images-webp-smaller/kate-trysh.webp
  static/images/mosaic-images-webp-smaller/lawrence-hookham.webp
  static/images/mosaic-images-webp-smaller/madrona-rose.webp
  static/images/mosaic-images-webp-smaller/olga-nayda.webp
  static/images/mosaic-images-webp-smaller/sudo.webp
  static/images/mosaic-images-webp-smaller/tiago-rosado.webp
  templates/base.html
  templates/dashboard/index.html
Labels: front

#37 add class to hide content on larger screens
  templates/base.html
Labels: front

#38 add links to buttons and style
  static/css/dashboard/style.css
  static/css/style.css
  templates/dashboard/index.html
Labels: front

#39 add message on larger devices
  templates/base.html
Labels: front

#44 Header nav-bar display only for mobile
  git
  templates/base.html
Labels: front

#46 style register and login forms
  .gitignore
  static/css/style.css
  templates/allauth/account/login.html
  templates/allauth/account/signup.html
Labels: front

#49 feat: add js and geolocation functions
  static/css/style.css
  static/js/script.js
  templates/base.html
Labels: front

#51 Add score to user
  challenge/urls.py
  challenge/views.py
  db.sqlite3
  static/js/script.js
  templates/challenge/challenge.html
Labels: front, back

#54 bug:make fetch dynamic
  static/js/script.js
Labels: bug, front

#59 bug: remove pos fixed so pages scroll
  static/css/style.css
Labels: bug, front

#65 feat:add locations page with cards
  static/css/dashboard/style.css
  static/css/location/style.css
  templates/location/location.html
Labels: front

#68 style:my points page and rearrange menu items
  templates/base.html
  templates/leaderboard/mypoints.html
Labels: front

#66 feat:sort and style leaderboard
  templates/leaderboard/leaderboard.html
Labels: front
